src/Entity/CompteJournaux.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompteJournauxRepository")
 */
class CompteJournaux
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Recette", mappedBy="codeJournaux")
     */
    private $recettes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Detaildepense", mappedBy="caisseCentrale")
     */
    private $depenses;


    public function __construct()
    {
        $this->recettes = new ArrayCollection();
        $this->depenses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

   

    public function getRecettes():?float
    {
        $totalRecette=0;
        foreach($this->recettes as $uneRecette)
        $totalRecette+= $uneRecette->getMontantrecette();
        return $totalRecette;
    }

    public function getDepenses():?float
    {
        $totalDepense=0;
       //if(is_array($this->depenses)){
         foreach($this->depenses as $uneDepense)
          $totalDepense += $uneDepense->getMontantdetail();
            return $totalDepense;
       //}else{
       //   return  $totalDepense=0;
       // }
       
    }
   
    public function getLeSolde()
    {
        return $this->getRecettes() - $this->getDepenses();
    }

}

src/Entity/Plantresorerie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlantresorerieRepository")
 */
class Plantresorerie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Previsionbudget")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $lignebudget;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank
     */
    private $besoin;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $realisation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Observation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateFin;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $valider;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLignebudget(): ?Previsionbudget
    {
        return $this->lignebudget;
    }

    public function setLignebudget(?Previsionbudget $lignebudget): self
    {
        $this->lignebudget = $lignebudget;

        return $this;
    }

    public function getBesoin(): ?float
    {
        return $this->besoin;
    }

    public function setBesoin(float $besoin): self
    {
        $this->besoin = $besoin;

        return $this;
    }

    public function getRealisation(): ?float
    {
        return $this->realisation;
    }

    public function setRealisation(?float $realisation): self
    {
        $this->realisation = $realisation;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->Observation;
    }

    public function setObservation(?string $Observation): self
    {
        $this->Observation = $Observation;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getValider(): ?bool
    {
        return $this->valider;
    }

    public function setValider(bool $valider): self
    {
        $this->valider = $valider;

        return $this;
    }
}

src/Form/DepenseType.php
<?php

namespace App\Form;

use App\Entity\Depense;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DepenseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libele')
            ->add('montantdepense')
            ->add('utilisateurdepense')
            ->add('service')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Depense::class,
        ]);
    }
}

src/Controller/DepenseController.php
<?php

namespace App\Controller;

use App\Entity\Depense;
use App\Entity\Service;
use App\Entity\Personne;
use App\Entity\Etatbesoin;
use App\Entity\Detaildepense;
use App\Entity\Anneebudgetaire;
use App\Entity\Previsionbudget;
use Doctrine\DBAL\Types\FloatType;
use Doctrine\ORM\EntityRepository;
use App\Repository\EtatbesoinRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DepenseController extends AbstractController{

/**
 * @Route("/sgb/depense/addOp", name="depense_Op")
 * @Route("/sgb/depense/addOp/{id}/edit", name="op_edit")
 */
public function frmOp(Session $session, Depense $unedepense = null, Request $request, ObjectManager $manager){
    if($this->getUser()===null) {              
        return $this->redirectToRoute('user_login');
    }
    if(!$unedepense){
        $unedepense= new Depense();
    }
    
    // Service
   if( $this->isGranted('ROLE_COMPTE_FAC') or $this->isGranted('ROLE_CHEF_SERVICE') ){
    $session->set('servicesselectOp', $this->getUser()->getServices()->getId() );
    $service= $session->get('servicesselectOp');
    }else{
    // Service
    if($request->request->get('services')!==null && $request->request->get('services') <> $session->get('servicesselectOp') ){
        $session->set('servicesselectOp',$request->request->get('services') );
    }
    $service= $session->get('servicesselectOp');
    }


    // Année budgetaire
    if($request->request->get('annees')!==null && $request->request->get('annees') <> $session->get('anneeselectOp') ){
        $session->set('anneeselectOp', $request->request->get('annees') );
    }
    $anneebudgetselect= $session->get('anneeselectOp');

    $em = $this->getDoctrine()->getManager();
    $frmDepense= $this->createFormBuilder($unedepense)
            
            ->add('id', HiddenType::class
                ,['mapped'=> false])
            ->add('libele')
            ->add('createAt', DateType::class, array(
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd',
                'label'=>'Date enregistrement'
            ))
            ->add('montantdepense', NumberType::class, array(
                'label'=>'Montant'
            ))
            ->add('utilisateurdepense', EntityType::class, array(
                'class'  => Personne::class,
               
                'query_builder'=>function(EntityRepository $er)use ( $unedepense) {
                    if($this->isGranted('ROLE_COMPTE_FAC')){
                            return $er->createQueryBuilder('p')
                            ->select("p")
                            ->where("p.id=:user")
                            ->setParameter('user',  $unedepense->getUtilisateurdepense()!== $this->getUser()? 
                            $unedepense->getUtilisateurdepense(): $unedepense === null? $this->getUser():$this->getUser()
                             );
                    }elseif($this->isGranted('ROLE_COMPTABILITE')){
                        return $er->createQueryBuilder('p')
                        ->select("p");
                    }elseif($this->isGranted('ROLE_RECTOR') or $this->isGranted('ROLE_SG') or $this->isGranted('ROLE_AB') or $this->isGranted('ROLE_CHEF_SERVICE')){
                        return $er->createQueryBuilder('p')
                        ->select("p")
                        ->where("p.id=:userdepense")
                        ->setParameter('userdepense', $unedepense->getUtilisateurdepense());
                    }
                },               
               
                'choice_label'=>'nom',
                'label'=>'Comptable'
            ))
            ->add('numOp', TextType::class, [
                
                'label'=>'Numéro OP',
            ])
            ->add('dateEmission', DateType::class, array(
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd',
                'label'=>'Date emission'
            ))
            ->add('modePaiement', ChoiceType::class, [
                'choices'=>[
                    'CASH'=>'CASH',
                    'CHEQUE'=>'CHEQUE',
                    'VIREMENT'=>'VIREMENT'
                ],
                'placeholder'=>'Mode de paiement'
            ])
            ->add('beneficiaire', TextType::class, [
                'attr'=>[
                'placeholder'=>'Nom du bénéficiaire',
                ]
            ])
            ->add('chefDepartement', TextType::class, [
                'attr'=>[
                'placeholder'=>'Chef de Service', 
                'required'=> false,
                ]
            ])
            ->add('secGeneralConcerne', TextType::class, [
                'attr'=>[
                'placeholder'=>'Secrétaire Gén. Concerné',
               
                ]
            ])
            ->add('abOuDelegue', TextType::class, [
                'attr'=>[
                'placeholder'=>'AB ou son délégué',
               
                ],  'required'=> false,
            ])
            ->add('recteurOuDelegue', TextType::class, [
                'attr'=>[
                'placeholder'=>'Recteur ou son délégué',
                'required'=> false,
                ]
            ])

            ->add('autoriserChefService', CheckboxType::class, [
               
                'label'=>'Autorisation du Chef de Service',
             
            ])
            ->add('autoriserSG', CheckboxType::class, [
               
                'label'=>'Autorisation du SG',
               
            ])
            ->add('autoriserAB', CheckboxType::class, [
               
                'label'=>'Autorisation de l\'AB',
                 
            ])
            ->add('autoriserRecteur', CheckboxType::class, [
               
                'label'=>'Autorisation du Recteur',
               
            ])
            ->add('isCentralyzed', CheckboxType::class, [
               
                'label'=>'Centraliser',
                
            ])

            ->add('ligneBudgetaire', EntityType::class, array(
                'class'=>Previsionbudget::class,
                'query_builder'=>function(EntityRepository $er)use ($anneebudgetselect, $service) {
            if( $this->isGranted('ROLE_COMPTE_FAC') or $this->isGranted('ROLE_CHEF_SERVICE') ){
                 return $er->createQueryBuilder('p') 
                            ->select("p, l")
                            ->join("p.lignebudgetprevision", 'l')
                            ->join("p.anneebudgetprevision", 'a')
                            ->where("p.iscentraliser=false AND p.isValideted=true AND p.service=:userservice AND l.categorieLigne = :ladepense AND a.id = :annnebudget")
                            ->setParameter('userservice',$service)
                            ->setParameter('ladepense','Depense')
                            ->setParameter('annnebudget', $anneebudgetselect);
            }else{
                return $er->createQueryBuilder('p') 
                ->select("p, l")
                ->join("p.lignebudgetprevision", 'l')
                ->join("p.anneebudgetprevision", 'a')
                ->where("p.isValideted=true AND p.service=:userservice AND l.categorieLigne = :ladepense AND a.id = :annnebudget")
                ->setParameter('userservice',$service)
                ->setParameter('ladepense','Depense')
                ->setParameter('annnebudget', $anneebudgetselect);
            }
                            },
                            'choice_label'=>function( Previsionbudget $previsionbudget) {
                                //revoie uniquement les lignes de depense dont il le solde est >0
                                return    $previsionbudget->getLeSoldeEnPrevision()<=0?false: $previsionbudget->getLeSoldeEnPrevision()."$ /". $previsionbudget->getLignebudgetprevision()->getIntituleLigne();
                        },'group_by' => function($previsionbudget, $key, $value) {
                               return $previsionbudget->getLeSoldeEnPrevision()<=0 ?false: 'Previsions';
                        },
                            )) 
            ->add('service', EntityType::class, array(
                'class'  => Service::class,
                'query_builder'=>function(EntityRepository $er)use ( $service, $em) {
                    if($this->isGranted('ROLE_COMPTE_FAC') or $this->isGranted('ROLE_CHEF_SERVICE')){
                            return $er->createQueryBuilder('s')
                            ->select("s")
                            ->where("s.id=:userservice")
                            ->setParameter('userservice',  $this->getUser()->getServices());
                    }elseif($this->isGranted('ROLE_COMPTABILITE') or $this->isGranted('ROLE_RECTOR') or $this->isGranted('ROLE_SG') or $this->isGranted('ROLE_AB')){
                        return $er->createQueryBuilder('s')
                        ->select("s")
                        ->where("s.id=:userservice")
                        ->setParameter('userservice',  $service);
                    }
                },               

src/Controller/SGBHelper.php
<?php

namespace App\Controller;


use App\Entity\LigneBudgetaire;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class SGBHelper implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        // Tells the dispatcher that you want to listen on the form.pre_set_data
        // event and that the preSetData method should be called.
        return array(FormEvents::PRE_SET_DATA => 'preSetData');
    }

    public function preSetData(FormEvent $event)
    {
        $lignebudgetaire = $event->getData();
        $form = $event->getForm();

        if (!$lignebudgetaire || null === $lignebudgetaire->getId()) {

            $form->add('lignebudgetprevision', EntityType::class, array(
                'class'  => LigneBudgetaire::class,
                'placeholder'=>'Choisissez une ligne',
                'query_builder'=>function(EntityRepository $er){
                    return $er->createQueryBuilder('u')
                                ->where('u.categorieLigne=:thisCat')
                                ->setParameter('thisCat',$form->getDate()->getCategorieLine());
                },
                'choice_label'=>'intituleLigne'
            ));
        }
    }
}

templates/sgb/depense/depense.html.twig
{% extends 'base.html.twig' %}
{% form_theme frmDepense 'bootstrap_4_layout.html.twig' %}
{% block body %}
    <table>
        <tbody>
            <tr>
                <td></td>
                <td>
                    <h3>Depense
                    </h3>
                    <table class="table table-hover">
                        <thead>
                            <tr class="table-primary">
                                <th scope="col">ID</th>
                                <th scope="col">Compte</th>
                                <th scope="col">Libelé depense</th>
                                <th scope="col">Prévisions</th>
                                <th scope="col">Réalisations</th>
                                <th scope="col">Ecarts</th>
                                <th scope="col">Taux de réalisation</th>
                                <th scope="col">Service</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% set numDepense = 0 %}
                            {% set totalePrevision = 0 %}
                            {% set totaleRealisation = 0 %}
                            {% set totaleSortie = 0 %}
                            {% for dep in queryDepenseGlobale %}
                           
                                <tr>
                                    <th scope="row">
                                        {% set numDepense = numDepense + 1 %}
                                        {{ numDepense }}
                                    </th>
                                    <td>
                                        {{dep.mesdep.lignebudgetdepense.lignebudgetprevision.compteLigne }}</td>
                                    <td>
                                        {{dep.mesdep.lignebudgetdepense.lignebudgetprevision.intituleLigne}}</td>
                                    <td>
                                        {{dep.mesdep.lignebudgetdepense.montantprevision|number_format(2, '.',',')}}</td>
                                         {% set totalePrevision = totalePrevision + dep.mesdep.lignebudgetdepense.montantprevision %}
                                    {% if dep.sommedepense > dep.mesdep.lignebudgetdepense.montantprevision %}
                                        
                                            <td><h6 style="color:red">
                                                {{dep.sommedepense|number_format(2, '.',',')}} </h6></td>
                                            <td><h6 style="color:red">
                                                {{(dep.mesdep.lignebudgetdepense.montantprevision - dep.sommedepense)|number_format(2, '.',',')}}</h6></td>
                                            <td><h6 style="color:red">
                                                {% if dep.mesdep.lignebudgetdepense.montantprevision > 0 %}
                                                    {{((dep.sommedepense / dep.mesdep.lignebudgetdepense.montantprevision ) * 100 )|number_format(2, '.', ',') }}%
                                                {% endif %}</h6>
                                            </td>
                                       
                                        {% else %}
                                        <td>
                                            {{dep.sommedepense   |number_format(2, '.',',')}}</td>
                                        <td>
                                            {{(dep.mesdep.lignebudgetdepense.montantprevision - dep.sommedepense)|number_format(2, '.',',')}}</td>
                                        <td>
                                            {% if dep.mesdep.lignebudgetdepense.montantprevision > 0 %}
                                                {{((dep.sommedepense / dep.mesdep.lignebudgetdepense.montantprevision ) * 100 )|number_format(2, '.', ',') }}%
                                            {% endif %}
                                        </td>
                                    {% endif %}
                                    {% set totaleSortie = totaleSortie + dep.sommedepense %}
                                  
                                    <td>
                                        {{dep.mesdep.lignebudgetdepense.service.designation }}
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr class="table-primary">
                                <th scope="row"></th>
                                <td></td>
                                <td></td>
                                <td>{{totalePrevision|number_format(2, '.', ',')}}</td>
                                <td>
                                    {{totaleSortie|number_format(2, '.', ',')}}
                                </td>
                                <td>{{(totalePrevision - totaleSortie)|number_format(2, '.', ',')}} </td>
                                <td> {% if totalePrevision > 0 %}
                                                {{((totaleSortie / totalePrevision ) * 100 )|number_format(2, '.', ',') }}%
                                            {% endif %}</td>
                                <td colspan="1">
                                    {{ converssion(totaleSortie, "USD") }}</td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <td></td>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/sgb/depense/etatCaisse.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   <h5> La situation de la caisse </h5>
      <a class="btn btn-success" href="{{path('depense_Op')}}">Retour à l'OP</a>

{% if resultatIsCentralized[0].central is same as(true) %}
                       
                             <table class="table table-hover">
                                <thead>
                                    <tr class="table-primary">
                                        <th scope="col">ID </th>
                                        <th scope="col">Code</th>
                                        <th scope="col">intitule</th>
                                        <th scope="col">montant</th>
                                    </tr>
                                </thead>
                                <tbody>

                                 {% set numDepense = 0 %}
                                    {% set totalCaisse = 0 %}
                                     {% for caisse in resultatCaisseCentrale %}
                                     
                                            <tr>
                                                <th scope="row">
                                                    {% set numDepense = numDepense + 1 %}
                                                    {{ numDepense }}
                                                </th>
                                                <td>
                                              
                                                    {{caisse.soldeCaisse.codeJournaux.code}}
                                                    {% set totalCaisse = totalCaisse + caisse.soldeCaisse.codeJournaux.leSolde %}
                                                </td>
                                                <td>
                                                    {{caisse.soldeCaisse.codeJournaux.intitule}}
                                                </td>
                                                <td>
                                                    {{ caisse.soldeCaisse.codeJournaux.leSolde|number_format(2, '.',',')}}
                                                </td>
                                                </tr>
                             {% endfor %}
                             <tr class="table-primary">
                                                <th scope="row"></th>
                                                <td></td>
                                                <td>Total
                                                </td>
                                                <td>
                                                    {{totalCaisse|number_format(2, '.',',')}}</td>
                                            </tr>
                                                </tbody>
                        </table>
                                            {% else %}





                         <table class="table table-hover">
                            <thead>
                                <tr class="table-primary">
                                    <th scope="col">ID</th>
                                    <th scope="col">Service</th>
                                    <th scope="col">recette</th>
                                    <th scope="col">montant</th>
                                </tr>
                            </thead>
                            <tbody>
                              {% set numDepense = 0 %}
                               {% set soldeService = 0 %}
                              {% set service = null %}
                                {% for soldeLigne in querySoldeCompte %}
                                  {% if soldeLigne.mesrecettes.lignebudgetrecette.leSolde > 0 %}
                                   <tr>
                                       <th scope="row">
                                             {% set numDepense = numDepense + 1 %}
                                        {{ numDepense }}
                                       </th>
                                        <td>
                                            {{soldeLigne.mesrecettes.lignebudgetrecette.service.designation}}
                                            {% set service = soldeLigne.mesrecettes.lignebudgetrecette.service %}
                                        </td>
                                        <td>
                                            {{soldeLigne.mesrecettes.lignebudgetrecette.lignebudgetprevision.intituleLigne}}
                                        </td>
                                        <td>
                                            {% set soldeService = soldeService + soldeLigne.mesrecettes.lignebudgetrecette.leSolde %}
                                            {{soldeLigne.mesrecettes.lignebudgetrecette.leSolde}}
                                        </td>
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                                <tr class="table-primary">
                                <th scope="row"></th>
                                <td></td>
                                <td>Reste en caisse</td>
                                <td>{{soldeService}}</td>
                            </tr>
                             {% if ( is_granted('ROLE_CHEF_SERVICE')== false) or ( is_granted('ROLE_COMPTE_FAC')== false)  %}
                                    {% set numDepenseAutre = 0 %}
                                    {% set soldeAutresService = 0 %}
                                        {% if querySoldeCompteAutres is defined %}
                                        
                                        {% for soldeLigneAutre in querySoldeCompteAutres %}
                                            {% if soldeLigneAutre.mesrecettes.lignebudgetrecette.leSolde > 0  and soldeLigneAutre.mesrecettes.lignebudgetrecette.service is not same as(service) %}
                                                <tr>
                                                        <th scope="row">
                                                            {% set numDepenseAutre = numDepenseAutre + 1 %}
                                                            {{ numDepenseAutre }}
                                                        </th>
                                                        <td>
                                                            {{soldeLigneAutre.mesrecettes.lignebudgetrecette.service.designation}}
                                                        </td>
                                                        <td>
                                                            {{soldeLigneAutre.mesrecettes.lignebudgetrecette.lignebudgetprevision.intituleLigne}}
                                                        </td>
                                                        <td>
                                                            {% set soldeAutresService = soldeAutresService + soldeLigneAutre.mesrecettes.lignebudgetrecette.leSolde %}
                                                            {{soldeLigneAutre.mesrecettes.lignebudgetrecette.leSolde}}
                                                        </td>
                                                </tr>
                                            {% endif %}
                                    {% endfor %}
                                   
                                    <tr class="table-primary">
                                    <th scope="row"></th>
                                    <td></td>
                                    <td>Reste Autre </td>
                                    <td>{{soldeAutresService}}</td>
                                    </tr>
                                    <tr class="table-primary">
                                    <th scope="row"></th>
                                    <td></td>
                                    <td>Reste Global </td>
                                    <td>{{soldeAutresService + soldeService}}</td>
                                    </tr>
                                     {% endif %}
                                {% endif %}
                            </tbody>
                        </table>
                        {% endif %}
                        {% endblock %}